# Generated by Django 4.2.4 on 2023-08-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_comment_created_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
