# Generated by Django 4.2.4 on 2023-09-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
