# Generated by Django 4.2.4 on 2023-10-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_remove_userprofile_profile_picture_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
