# Generated by Django 4.2.4 on 2023-10-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_profile_bio_profile_photo_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='profile_image',
        ),
    ]
