# Generated by Django 4.2.4 on 2023-10-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0030_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
