# Generated by Django 4.2.4 on 2023-10-14 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0041_alter_message_options_rename_timestamp_message_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(to='social.message'),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='social.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.message')),
            ],
            options={
                'unique_together': {('conversation', 'message')},
            },
        ),
    ]
