# Generated by Django 4.2.4 on 2023-10-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0044_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
