# Generated by Django 4.2.4 on 2023-10-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0046_rename_views_count_story_unique_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
