# Generated by Django 4.2.4 on 2023-10-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0050_remove_message_thread_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='social.profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='social.profile'),
        ),
    ]
