# Generated by Django 4.2.4 on 2023-10-22 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0052_profile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
