# Generated by Django 4.2.4 on 2023-10-22 20:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0054_alter_profile_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
