# Generated by Django 4.2.4 on 2023-10-23 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0056_remove_profile_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
