# Generated by Django 4.2.4 on 2023-10-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0059_profile_view_count_profile_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='views',
        ),
    ]
